### ISSUE TITLE
Wrong example output in README

### ISSUE THREAD

**Issue by BrunoPanizzi** [tsoding/tula#4]
Under the section about "Sets and Universal Quantification", there is an example about nested quantifiers: 

> ```js
> let Set { a b c }
> for n in Set
> for m in Set
> case (S n) m 0 -> S
> ```
> 
> The above expands to this:
> 
> ```js
> case (S a) a a -> S
> case (S a) b a -> S
> case (S a) c a -> S
> case (S b) a b -> S
> case (S b) b b -> S
> case (S b) c b -> S
> case (S c) a c -> S
> case (S c) b c -> S
> case (S c) c c -> S
> ```

But the expanded result doesn't match the code, either the `0` in the code should be changed to `n` or the expanded version should be changed. Personally I think the first option makes more sense with the example.

**Comment by rexim** [comment]
Thank you for catching the mistake!
